[ucenter]
secret=123456

[database]
driverName = "mysql"
host = "127.0.0.1"
port=3306
database = "test"
user = "root"
password = 123456
#连接池配置
max_conn_life_time  = 60
max_idle_conn  = 10
max_open_conn = 10
#数据源参数配置
charset = "utf8"
parseTime = true
local = "Local"

[redis]
addr = "127.0.0.1"
port=6379
maxIdle = 2
maxActive = 5
timeout = 20